name: Renew Five Tips Every Admin Should Know About VS Code Dev Org Lease
run-name: ${{ github.actor }} triggered dev org renewal build
#on: [push]
on:
  schedule:
    - cron:  '30 20 * * MON'
  workflow_dispatch:
jobs:
  dev-org-renew:
    runs-on: ubuntu-latest
    environment: AuthorizedProjectOrg
    steps:
      - uses: actions/checkout@v4
        with: 
          ref: main
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: 'Install CLI'
        run: npm install @salesforce/cli --location=global
      - run: sf --version
      - name: 'Authenticate to Five Tips Every Admin Should Know About VSCode org'
        run: |
            echo ${{ secrets.FIVETIPSURL}} > ./FIVETIPSURL.txt
            ls -al ./FIVETIPSURL.txt
            sf org login sfdx-url -f ./FIVETIPSURL.txt -a AuthorizedProjectOrg -d
      - name: 'Query data'
        run: |
            sf data query --query "select name from organization" -o AuthorizedProjectOrg